apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
spec:
  project: applications
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: grafana
    targetRevision: 10.4.0
    helm:
      releaseName: grafana
      values: |
        ingress:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

