apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  project: applications
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: 6.49.0
    helm:
      releaseName: loki-db
      values: |
       loki:
         auth_enabled: false
         storage:
           type: filesystem
       limits_config:
         retention_period: 720h  # 30 days
       singleBinary:
         replicas: 1
       serviceMonitor:
         enabled: true


  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

