apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  project: applications
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: 6.49.0
    helm:
      releaseName: loki-db
      values: |
       deploymentMode: SingleBinary
       loki:
         commonConfig:
           replication_factor: 1
         auth_enabled: false
         storage:
           type: filesystem
         schemaConfig:
           configs:
             - from: 2024-04-01
               object_store: filesystem
               store: tsdb
               schema: v13
               index:
                 prefix: index_
                 period: 24h
       limits_config:
         retention_period: 720h  # 30 days
       write:
         replicas: 0
       read:
         replicas: 0
       backend:
         replicas: 0
       singleBinary:
         replicas: 1
       serviceMonitor:
         enabled: true


  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

