{{ $root := . }}
{{- range $vm := .Values.vms }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ $vm.name }}
  namespace: {{ $root.Values.namespace }}
spec:
  storageClassName: longhorn-la
  dataSource:
    name: {{ $vm.dvSource }}
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $vm.disk.size }}
---
{{- end }}
